services:
  - type: web
    name: travelagency
    env: node
    plan: free
    rootDir: TravelAgency
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_SETUP_KEY
        value: travelagency-admin-key
      - key: ADMIN_ACCESS_CODE
        value: Ashu2406
